spring.application.name=WeatherVisualization



spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/weather_visualization?reWriteBatchedInserts=true}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}
python.pdf.service.url=${PYTHON_PDF_URL:http://localhost:8000/generate-pdf}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
security.jwt.secret=${JWT_SECRET}
server.port=${PORT:8080}



spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB


# Pakowanie insertow w paczki po 50 sztuk
spring.jpa.properties.hibernate.jdbc.batch_size=50
# Grupowanie insertow
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
