spring.application.name=WeatherVisualization



spring.datasource.url=jdbc:postgresql://localhost:5432/weather-visualization?reWriteBatchedInserts=true
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
security.jwt.secret=${JWT_SECRET}



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


# Pakowanie insertow w paczki po 50 sztuk
spring.jpa.properties.hibernate.jdbc.batch_size=50
# Grupowanie insertow
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
